import {
  Alarm,
  Armchair,
  BatteryCharging,
  Bathtub,
  Bed,
  BellSimple,
  Binoculars,
  Broom,
  Buildings,
  CalendarCheck,
  CallBell,
  Check,
  Cigarette,
  CoatHanger,
  Coffee,
  CookingPot,
  Couch,
  Cube,
  Desk,
  Door,
  Drop,
  DropHalf,
  Elevator,
  Eye,
  Fan,
  FireExtinguisher,
  FirstAidKit,
  ForkKnife,
  Hand,
  HandSoap,
  Key,
  Laptop,
  Lightning,
  Moon,
  Mountains,
  Phone,
  Plugs,
  PlugsConnected,
  Ruler,
  SecurityCamera,
  ShieldCheck,
  Shower,
  SolarPanel,
  SpeakerHigh,
  Stairs,
  Sun,
  SwimmingPool,
  TeaBag,
  Television,
  TelevisionSimple,
  ThermometerHot,
  Toilet,
  Towel,
  Tree,
  TShirt,
  Users,
  UsersThree,
  Vault,
  Wallet,
  Waves,
  Wheelchair,
  WheelchairMotion,
  WifiHigh,
  Wind,
  Wine,
} from "@phosphor-icons/react/ssr";
import type { Icon } from "@phosphor-icons/react";
import { createElement } from "react";
import { amenityIcon } from "../ui/amenity";

/**
 * The API names each amenity, fact and included item's icon by its Phosphor component name
 * (API-ROOMS 2). Only names in this table are drawn; anything else falls back to the keyword
 * match on the label, then a tick, so a new catalogue entry never breaks the page.
 */
const ICONS: Record<string, Icon> = {
  Alarm,
  Armchair,
  BatteryCharging,
  Bathtub,
  Bed,
  BellSimple,
  Binoculars,
  Broom,
  Buildings,
  CalendarCheck,
  CallBell,
  Check,
  Cigarette,
  CoatHanger,
  Coffee,
  CookingPot,
  Couch,
  Cube,
  Desk,
  Door,
  Drop,
  DropHalf,
  Elevator,
  Eye,
  Fan,
  FireExtinguisher,
  FirstAidKit,
  ForkKnife,
  Hand,
  HandSoap,
  Key,
  Laptop,
  Lightning,
  Moon,
  Mountains,
  Phone,
  Plugs,
  PlugsConnected,
  Ruler,
  SecurityCamera,
  ShieldCheck,
  Shower,
  SolarPanel,
  SpeakerHigh,
  Stairs,
  Sun,
  SwimmingPool,
  TeaBag,
  Television,
  TelevisionSimple,
  ThermometerHot,
  Toilet,
  Towel,
  Tree,
  TShirt,
  Users,
  UsersThree,
  Vault,
  Wallet,
  Waves,
  Wheelchair,
  WheelchairMotion,
  WifiHigh,
  Wind,
  Wine,
};

/** A view fact draws the kind of view it is. */
const VIEW_ICON: [RegExp, Icon][] = [
  [/lagoon|ocean|sea|beach/i, Waves],
  [/garden|courtyard/i, Tree],
  [/pool/i, SwimmingPool],
  [/city/i, Buildings],
];

export function roomIcon(name: string, label = ""): Icon {
  if (name === "Mountains" || /view$/i.test(label)) for (const [re, icon] of VIEW_ICON) if (re.test(label)) return icon;
  return ICONS[name] ?? (label ? amenityIcon(label) : Check);
}

export function RoomIcon({ name, label, size = 18, className = "", weight = "light" }: { name: string; label?: string; size?: number; className?: string; weight?: "light" | "regular" | "thin" | "bold" | "fill" | "duotone" }) {
  // Picked from a static table, so creating the element here is safe.
  return createElement(roomIcon(name, label), { size, weight, className, "aria-hidden": true });
}
